# Copyright 2026 Ant International, Ant Group Co., Ltd.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Author (Xiaojian Liang)

load("//bazel:mosac.bzl", "mosac_cc_library", "mosac_cc_test")

package(default_visibility = ["//visibility:public"])

mosac_cc_library(
    name = "cr_param",
    srcs = [],
    hdrs = [
        "param.h",
    ],
)

mosac_cc_library(
    name = "fake_cr",
    srcs = [
        "fake_cr.cc",
    ],
    hdrs = [
        "fake_cr.h",
    ],
    deps = [
        ":cr",
        "//mosac/context",
        "//mosac/context:state",
        "//mosac/ss:ss_type",
        "//mosac/utils:field",
        "//mosac/utils:vec_op",
    ],
)

mosac_cc_library(
    name = "true_cr",
    srcs = [
        "true_cr.cc",
    ],
    hdrs = [
        "true_cr.h",
    ],
    deps = [
        ":cr",
        ":cr_param",
        "//mosac/context",
        "//mosac/context:state",
        "//mosac/cr/utils:ot_adapter",
        "//mosac/cr/utils:ot_helper",
        "//mosac/cr/utils:vole_adapter",
        "//mosac/ss:ss_type",
        "//mosac/utils:field",
        "//mosac/utils:vec_op",
    ],
)

mosac_cc_library(
    name = "cr",
    srcs = [
        "cr.cc",
    ],
    hdrs = [
        "cr.h",
    ],
    deps = [
        ":cr_param",
        "//mosac/context",
        "//mosac/context:state",
        "//mosac/ss:ss_type",
        "//mosac/utils:field",
        "//mosac/utils:vec_op",
    ],
)

mosac_cc_test(
    name = "cr_test",
    srcs = ["cr_test.cc"],
    deps = [
        ":cr",
        ":fake_cr",
        ":true_cr",
        "//mosac/context:register",
        "//mosac/ss:ss_type",
        "//mosac/utils:test_util",
    ],
)
